name: Test Self-Hosted Runner

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  workflow_dispatch:
  push:
    branches: ['master', 'main']

jobs:
  test-runner:
    runs-on: self-hosted 
    
    steps:
      - name: Check runner connection
        run: |
          echo "✅ Runner is working!"
          echo "Hostname: $(hostname)"
          echo "OS: $(uname -a)"
          echo "Docker: $(docker --version || echo 'Docker not available')"
          echo "Disk: $(df -h | grep -v tmpfs)"